# CI that:
#
# * checks for a Git Tag that looks like a release
# * creates a Github Release™ and fills in its text
# * builds artifacts with cargo-dist (executable-zips, installers)
# * uploads those artifacts to the Github Release™
#
# Note that the Github Release™ will be created before the artifacts,
# so there will be a few minutes where the release has no artifacts
# and then they will slowly trickle in, possibly failing. To make
# this more pleasant we mark the release as a "draft" until all
# artifacts have been successfully uploaded. This allows you to
# choose what to do with partial successes and avoids spamming
# anyone with notifications before the release is actually ready.
name: Release

permissions:
  contents: write

# This task will run whenever you push a git tag that looks like a version
# like "v1", "v1.2.0", "v0.1.0-prerelease01", "my-app-v1.0.0", etc.
# The version will be roughly parsed as ({PACKAGE_NAME}-)?v{VERSION}, where
# PACKAGE_NAME must be the name of a Cargo package in your workspace, and VERSION
# must be a Cargo-style SemVer Version.
#
# If PACKAGE_NAME is specified, then we will create a Github Release™ for that
# package (erroring out if it doesn't have the given version or isn't cargo-dist-able).
#
# If PACKAGE_NAME isn't specified, then we will create a Github Release™ for all
# (cargo-dist-able) packages in the workspace with that version (this is mode is
# intended for workspaces with only one dist-able package, or with all dist-able
# packages versioned/released in lockstep).
#
# If you push multiple tags at once, separate instances of this workflow will
# spin up, creating an independent Github Release™ for each one.
#
# If there's a prerelease-style suffix to the version then the Github Release™
# will be marked as a prerelease.
on:
  push:
    tags:
      - "release/*"

jobs:
  release-builds:
    name: build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - x86_64-pc-windows-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - arm-unknown-linux-musleabihf
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: "7.29.0"
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: pnpm
          cache-dependency-path: tracker/pnpm-lock.yaml
      - name: Install tracker deps
        run: pnpm install
        working-directory: tracker
      - name: Build tracker
        run: pnpm build
        working-directory: tracker
      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: Get final build
        run: cross build --release --target ${{ matrix.target }}
        working-directory: service
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: ferrite-${{ matrix.target }}
          path: service/target/${{ matrix.target }}/release/ferrite*

  compile-release:
    name: Compile release
    runs-on: ubuntu-latest
    needs: [release-builds]
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Calculate version
        id: version
        run: |
          VERSION=$(echo ${{ github.ref_name }} | sed -E 's/^release[/](.*)$/\1/')
          echo version=${VERSION} | tee -a "$GITHUB_OUTPUT"
        # Downloaded artifacts are put into awkward folders, and they lose their permissions.
        # So let's collect them into a single directory and mark them as executable.
      - name: Collect downloaded artifacts
        run: |
          VERSION=${{ steps.version.outputs.version }}
          mkdir -p release-artifacts
          cp ferrite-aarch64-unknown-linux-musl/ferrite release-artifacts/ferrite.${VERSION}.linux-aarch64
          cp ferrite-arm-unknown-linux-musleabihf/ferrite release-artifacts/ferrite.${VERSION}.linux-armv6
          cp ferrite-armv7-unknown-linux-musleabihf/ferrite release-artifacts/ferrite.${VERSION}.linux-armv7
          cp ferrite-x86_64-pc-windows-gnu/ferrite.exe release-artifacts/ferrite.${VERSION}.windows-x86_64.exe
          cp ferrite-x86_64-unknown-linux-musl/ferrite release-artifacts/ferrite.${VERSION}.linux-x86_64
          chmod +x release-artifacts/*
        # Sign the artifacts! Ensures any downloaded artifacts came from this build process.
      - name: Sign and prepare artifacts
        run: |
          echo "${SIGNING_PRIVATE_KEY}" | gpg --import -

          cd release-artifacts
          for file in * ; do
            gpg --detach-sign "$file"
          done

          for file in *.linux-* ; do
            tar -acf "${file}.tar.xz" "$file"
          done
          for file in *.windows-* ; do
            zip "${file}.zip" "$file"
          done
        env:
          SIGNING_PRIVATE_KEY: ${{ secrets.SIGNING_PRIVATE_KEY }}
        # Create a draft release. The description can be manually created afterwards.
      - name: Make release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release-artifacts/*.tar.xz,release-artifacts/*.zip,release-artifacts/*.sig
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          allowUpdates: true
          updateOnlyUnreleased: true
          removeArtifacts: true
          commit: ${{ github.ref_name }}
          tag: release/${{ steps.version.outputs.version }}
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: seriousbug
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Log in to the Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: SeriousBug
          password: ${{ secrets.GITHUB_TOKEN }}
        # We need to put the binaries into specific folders then run the docker build with buildx
      - name: Prepare to build docker images
        run: |
          VERSION=${{ steps.version.outputs.version }}
          mkdir -p Docker/binaries/linux/amd64 Docker/binaries/linux/arm64 Docker/binaries/linux/arm/v6 Docker/binaries/linux/arm/v7
          cd Docker
          cp ../release-artifacts/ferrite-analytics.${VERSION}.linux-aarch64 binaries/linux/arm64/ferrite-analytics
          cp ../release-artifacts/ferrite-analytics.${VERSION}.linux-armv6 binaries/linux/arm/v6/ferrite-analytics
          cp ../release-artifacts/ferrite-analytics.${VERSION}.linux-armv7 binaries/linux/arm/v7/ferrite-analytics
          cp ../release-artifacts/ferrite-analytics.${VERSION}.linux-x86_64 binaries/linux/amd64/ferrite-analytics
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          tags: seriousbug/ferrite-analytics:latest,seriousbug/ferrite-analytics:${{ steps.version.outputs.version }},ghcr.io/ferrite-analytics/ferrite-analytics:latest,ghcr.io/ferrite-analytics/ferrite-analytics:${{ steps.version.outputs.version }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          context: ./Docker
